### ISSUE TITLE
配置中遇到一些问题，麻烦作者给解决一下

### ISSUE THREAD

**Issue by lijian2033** [clayandgithub/zh_cnn_text_classify#1]
1、这是在巡行train文件时候提示的错误
问题：InvalidArgumentError (see above for traceback): Input to reshape is a tensor wit
h 8192 values, but the requested shape requires a multiple of 384
         [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:lo
输出提示信息为：
calhost/replica:0/task:0/cpu:0"](concat, Reshape/shape)]]
、Traceback (most recent call last):
  File "train.py", line 193, in <module>
    train_step(x_batch, y_batch)
  File "train.py", line 164, in train_step
    feed_dict)
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 778, in run
    run_metadata_ptr)
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape i
s a tensor with 8192 values, but the requested shape requires a multiple of 384
         [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:lo
calhost/replica:0/task:0/cpu:0"](concat, Reshape/shape)]]

Caused by op 'Reshape', defined at:
  File "train.py", line 108, in <module>
    l2_reg_lambda = FLAGS.l2_reg_lambda)
  File "C:\Users\Administrator\PycharmProjects\zh_cnn_text_classify-master\text_
cnn.py", line 56, in __init__
    self.h_pool_flat = tf.reshape(self.h_pool, [-1, num_filters_total])
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen
_array_ops.py", line 2510, in reshape
    name=name)
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framewo
rk\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framewo
rk\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "d:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framewo
rk\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()
InvalidArgumentError (see above for traceback): Input to reshape is a tensor wit
h 8192 values, but the requested shape requires a multiple of 384
         [[Node: Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:lo
calhost/replica:0/task:0/cpu:0"](concat, Reshape/shape)]]
2、在运行eval文件中input_label_file这个参数如何设置？
本人对这方面感兴趣，麻烦作者帮忙解决！！！

**Comment by clayandgithub** [comment]
1. 日志显示在self.h_pool_flat = tf.reshape(self.h_pool, [-1, num_filters_total])这一步出的问题，暂时不太清楚是什么原因造成的，请先把你修改后的filter_sizes、num_filters、batch_size以及卷积时设置的参数发出来看看吧，有可能程序有潜在的bug。
2. python eval.py --input_label_file /PATH_TO_INPUT_LABEL_FILE
说明：input_label_file中的每一行是0或1，需要与input_text_file中的每一行对应。
在eval.py中，如果有这个对照标签文件input_label_file，则会输出预测的准确率
