### ISSUE TITLE
环境配置问题,麻烦作者指导一下

### ISSUE THREAD

**Issue by Geek12580** [clayandgithub/zh_cnn_text_classify#19]
tensorflow 1.0.0
gensim 1.0.1这两个包我安装的版本不一样可以用吗?我用的是anaconda3.5,环境是Python2.7.13
然后我运行报错,小白不知道怎么解决.
/usr/anaconda3/envs/python27/bin/python2.7 /home/Snake/PycharmProjects/zh_cnn_text_classify/train.py
Traceback (most recent call last):
  File "/home/Snake/PycharmProjects/zh_cnn_text_classify/train.py", line 44, in <module>
    FLAGS._parse_flags()
  File "/usr/anaconda3/envs/python27/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/usr/anaconda3/envs/python27/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 472, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags

Process finished with exit code 1

**Comment by WillingDil** [comment]
https://blog.csdn.net/manduner/article/details/81103889
